use customer_behaviour;

select count(*) from customer_data;

select * from customer_data limit 20;

-- what is the total revenue generated by male vs female.

select gender,sum(purchase_amount) from customer_data
group by gender;

-- which customer used discount but still spent more than the avg purchase amount

select customer_id,purchase_amount from customer_data
where discount_applied = 'Yes' and purchase_amount >(select avg(purchase_amount) from customer_data);

-- top 5 products with highest review rating

select item_purchased,round(avg(review_rating), 2) as "Average product rating"from customer_data
group by item_purchased
order by item_purchased desc
limit 5;

-- compare average purchase amount between standard and express shipping

select shipping_type,round(avg(purchase_amount),2) from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

-- do subscribed customers spend more,compare avg and total btwn subscribers and non-subscribers

select subscription_status,count(customer_id) as total_customer,round(avg(purchase_amount), 2) as avg_purchase,sum(purchase_amount) as total_purchase
from customer_data
group by subscription_status
order by total_purchase,avg_purchase desc;

select subscription_status,count(customer_id) as total_customer,round(avg(purchase_amount), 2) as avg_purchase,sum(purchase_amount) as total_purchase
from customer_data
group by subscription_status;

-- which 5 products have the highest percentage of purchase with discount applied

select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate from customer_data
group by item_purchased
order by discount_rate desc
limit 5;

-- question 

with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_data    
    )
    
select customer_segment,count(*) as "Number of customers" from customer_type
group by customer_segment;    
    
-- top 3 most  purchased in each category

select category from customer_data
group by category;    
    
with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders from item_count
where item_rank <=3;

-- are customers who are reapeat buyers(more than 5 previous orders) aslo likely to subscribe

select subscription_status,count(customer_id) as repeat_buyers from customer_data
where previous_purchases > 5 
group by subscription_status;

-- revenue contribution of each age group

select age_group,sum(purchase_amount) as total_revenue from customer_data
group by age_group
order by total_revenue desc;